spring:
  profiles:
    group:
      prod1: profile1,common
      prod2: profile2,common
default:
  string: default property
---
spring:
  config:
    activate:
      on-profile: profile1
server:
  port: 8081

  servlet:
    encoding:
      charset: UTF-8
      force: true
security:
  require-ssl: true
---
spring:
  config:
    activate:
      on-profile: profile2
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
security:
  require-ssl: true
---
# 만약 스프링 시큐리티를 사용중이라면 아래 설정도 포함
security:
  require-ssl: true

spring:
  config:
    import: env.yml
    profiles: common

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:/org/springframework/batch/core/schema-mariadb.sql
    job:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/users/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            redirect-uri: "{baseUrl}/users/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: "http://ec2-3-38-67-125.ap-northeast-2.compute.amazonaws.com/users/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
---
logging:
  file:
    path: /log
